sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t robotronic0694/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true robotronic0694/docker-react-app npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'docker-react-app'
  env: 'Dockerreactapp-env'
  bucket_name: 'elasticbeanstalk-us-east-1-739806631164'
  bucket_path: 'docker-react-app'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
